function create(__helpers) {
  var str = __helpers.s,
      empty = __helpers.e,
      notEmpty = __helpers.ne;

  return function render(data, out) {
    out.w('<script type="text/ng-template" , id="templates/questions.html">\n  <md-content class=\'md-padding\'>\n    <div>\n      <md-grid-list\n          md-cols-sm=\'2\' md-cols-md=\'4\' md-cols-gt-md=\'6\' \n          md-row-height-gt-md=\'1:1\' md-row-height=\'4:3\'\n          md-gutter=\'8px\' md-gutter-gt-sm=\'4px\' >\n        <md-grid-tile ng-repeat=\'question in questions\' class=\'white md-whiteframe-z1\' md-rowspan=\'1\' md-colspan=\'2\' ng-cloak>\n          <md-grid-tile-header>\n            <h3><a ng-click=\'delete(question)\'><i class=\'fa fa-remove\'></i></a></h3>\n          </md-grid-tile-header>\n          <p class=\'question animated bounceIn\'>\n            <a ui-sref=\'edit({id: question.id})\'>\n              {{question.question}}\n            </a>\n          </p>\n          <md-grid-tile-footer>\n            <h3>\n              {{question.name}}\n            </h3>\n        </md-grid-tile>\n      </md-grid-list>\n    </div>\n  </md-content>\n  <md-button ui-sref=\'add\' class=\'md-primary md-fab md-fab-bottom-right\'>\n    ADD\n  </md-button>\n</script><script type="text/ng-template" , id="templates/addedit.html">\n  <md-content class=\'md-padding\'>\n    <h1>Ask a question</h1>\n      <form ng-submit=\'save(question)\'>\n        <div layout layout-sm=\'column\'>\n          <md-input-container flex>\n            <label>Your Name</label>\n            <input ng-model=\'question.name\'>\n          </md-input-container>\n        </div>\n        \n        <md-input-container flex>\n          <label>Question</label>\n          <textarea ng-model=\'question.question\' columns=\'1\' rows=\'4\' md-maxlength=\'150\'></textarea>\n        </md-input-container>\n        <md-button class=\'md-raised md-primary large-font\'>\n          Save Question\n        </md-button>\n        <md-button ui-sref=\'questions\' class=\'md-raised large-font\'>\n          Cancel\n        </md-button>\n      </form>\n    </md-content>\n</script>');
  };
}
(module.exports = require("marko").c(__filename)).c(create);